# ──────────── Font ────────────
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        15.0
disable_ligatures never

# ──────────── Cursor ────────────
#cursor_trail 1
#cursor_shape block
#cursor_blink true
cursor_blink true
cursor_shape beam
cursor_beam_thickness 7
cursor_blink_interval 600
cursor_stop_blinking_after 0
cursor_trail 1
cursor_trail_decay 0.18 0.35
cursor_trail_start_threshold 1
# ──────────── Window ────────────
window_padding_width 12
window_margin_width  12
window_border_width  0
corner_radius 12
dynamic_background_opacity yes

# ──────────── Transparency + Blur ────────────
background_opacity 0.70
blur_background yes
blur_radius 15
blur_method dual_kawase

# ──────────── Colors ────────────
background            #0c0c0c
foreground            #c5c8c6
selection_background  #222222

color0  #0c0c0c
color1  #ff5555
color2  #50fa7b
color3  #f1fa8c
color4  #bd93f9
color5  #ff79c6
color6  #8be9fd
color7  #bbbbbb
color8  #44475a
color9  #ff6e6e
color10 #69ff94
color11 #ffffa5
color12 #d6acff
color13 #ff92df
color14 #a4ffff
color15 #ffffff

# ──────────── Tabs ────────────
tab_bar_edge bottom
tab_bar_style hidden
tab_powerline_style slanted
tab_bar_min_tabs 0
placement_strategy center

active_tab_background   #1e1e2e
active_tab_foreground   #00ffff
inactive_tab_background #0c0c0c
inactive_tab_foreground #888888
active_tab_font_style bold
inactive_tab_font_style normal

# ──────────── Behavior ────────────
enable_audio_bell no
scrollback_lines 10000
confirm_os_window_close 0

# ──────────── Include Dracula Theme (optional) ────────────
include current-theme.conf
